config/routes.rb
Rails.application.routes.draw do
  resources :conditions
  resources :artists
  resources :albums
  resources :categories

  root to: "albums#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/condition.rb
class Condition < ApplicationRecord
  has_many :albums
  validates :name, presence: true, uniqueness: true
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
  before_action :set_condition, only: [:show, :edit, :update, :destroy]

  # GET /conditions
  # GET /conditions.json
  def index
    @search = Condition.ransack(params[:q])
    @conditions = @search.result(distinct: true).page(params[:page])
  end

  # GET /conditions/1
  # GET /conditions/1.json
  def show
  end

  # GET /conditions/new
  def new
    @condition = Condition.new
  end

  # GET /conditions/1/edit
  def edit
  end

  # POST /conditions
  # POST /conditions.json
  def create
    @condition = Condition.new(condition_params)

    respond_to do |format|
      if @condition.save
        format.html { redirect_to @condition, notice: 'Condition was successfully created.' }
        format.json { render :show, status: :created, location: @condition }
      else
        format.html { render :new }
        format.json { render json: @condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conditions/1
  # PATCH/PUT /conditions/1.json
  def update
    respond_to do |format|
      if @condition.update(condition_params)
        format.html { redirect_to @condition, notice: 'Condition was successfully updated.' }
        format.json { render :show, status: :ok, location: @condition }
      else
        format.html { render :edit }
        format.json { render json: @condition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conditions/1
  # DELETE /conditions/1.json
  def destroy
    @condition.destroy
    respond_to do |format|
      format.html { redirect_to conditions_url, notice: 'Condition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_condition
      @condition = Condition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def condition_params
      params.require(:condition).permit(:name)
    end
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/views/conditions/_form.html.erb
<%= form_for @condition, :html => { :class => "form-horizontal condition" } do |f| %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
      <%=f.error_span(:name) %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                conditions_path, :class => 'btn btn-info' %>
    </div>
  </div>

<% end %>

app/views/conditions/edit.html.erb
<%- model_class = Condition -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/conditions/index.html.erb
<%- model_class = Condition -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.pluralize.titleize %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_condition_path,
                :class => 'btn btn-primary pull-right' %>
  </h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%= t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @conditions.each do |condition| %>
      <tr>
        <td><%= link_to condition.id, condition_path(condition) %></td>
        <td><%= condition.name %></td>
        <td><%= l condition.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      condition_path(condition), :class => 'btn btn-info btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_condition_path(condition), :class => 'btn btn-info btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      condition_path(condition),
                      :method => :delete,
                      :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @conditions, :theme => 'twitter-bootstrap-3' %>

app/views/conditions/new.html.erb
<%- model_class = Condition -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/conditions/show.html.erb
<%- model_class = Condition -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @condition.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              conditions_path, :class => 'btn btn-info'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_condition_path(@condition), :class => 'btn btn-info' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              condition_path(@condition),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>