config/routes.rb
Rails.application.routes.draw do
  resources :conditions
  resources :artists
  resources :albums
  resources :categories

  root to: "albums#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :albums
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @search = Artist.ransack(params[:q])
    @artists = @search.result(distinct: true)
                      .includes(:albums)
                      .joins(:albums)
                      .page(params[:page])

  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @search = Album.ransack(params[:q])
    @albums = @search.result(distinct: true).page(params[:page])
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist, :html => { :class => "form-horizontal artist" } do |f| %>

  <% if @artist.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @artist.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
      <%=f.error_span(:name) %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                artists_path, :class => 'btn btn-info' %>
    </div>
  </div>

<% end %>

app/views/artists/edit.html.erb
<%- model_class = Artist -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/artists/index.html.erb
<%- model_class = Artist -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %>

    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_artist_path,
                :class => 'btn btn-primary pull-right' %>

  </h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sort_link @search, :id, model_class.human_attribute_name(:id) %></th>
      <th><%= sort_link @search, :name, model_class.human_attribute_name(:name) %></th>
      <th><%= sort_link @search, :created_at, model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= link_to artist.id, artist_path(artist) %></td>
        <td><%= artist.name %></td>

        <td><%=l artist.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      artist_path(artist), :class => 'btn btn-info btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_artist_path(artist), :class => 'btn btn-info btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      artist_path(artist),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @artists, :theme => 'twitter-bootstrap-3' %>

app/views/artists/new.html.erb
<%- model_class = Artist -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/artists/show.html.erb
<%- model_class = Artist -%>
<div class="page-header">
  <h1><strong><%= @artist.name %></strong></h1>

  <%= link_to t('.back', :default => t("helpers.links.back")),
              artists_path, :class => 'btn btn-info'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_artist_path(@artist), :class => 'btn btn-info' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              artist_path(@artist),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <div class="clearfix"></div>
  <br><br>
  <%= link_to 'Export to CSV',
              current_url(format: :csv),
              :class => 'pull-right' %>

</div>

<div class="col-lg-3 well">

  <%= search_form_for @search, :html => {:class => "form-horizontal album"} do |f| %>
    <div class="form-group">
      <%= f.label :title_cont %>
      <%= f.search_field :title_cont, placeholder: 'Ex: "The Best of.."', :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :condition_name, "Condition" %>
      <%= f.search_field :condition_name, placeholder: 'Ex: "New", "Good"', :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit 'Search', class: 'btn btn-info' %>
    </div>


  <% end %>

</div>
<div class="col-lg-9">


  <table class="table table-striped">
    <thead>
    <tr>
      <th><%= sort_link @search, :album_id, "ID" %></th>
      <th><%= sort_link @search, :album_title, model_class.human_attribute_name(:album_title) %></th>
      <th><%= sort_link @search, :album_year, model_class.human_attribute_name(:year) %></th>
      <th><%= sort_link @search, :record_condition, model_class.human_attribute_name(:record_condition) %></th>
      <th><%= model_class.human_attribute_name(:thumbnail) %></th>
      <th><%= sort_link @search, :created_at, model_class.human_attribute_name(:created_at) %></th>
      <th><%= t '.actions', :default => t("helpers.actions") %></th>
    </tr>
    </thead>
    <tbody>
    <% @albums.select { |a| a.artist_id == @artist.id}.each do |album| %>
      <% from_time = Time.now %>
      <tr>
        <td><%= album.id%></td>
        <td><%= album.title %></td>
        <td><%= album.year %></td>
        <td><%= album.condition_name %></td>
        <td><img src="<%= album.thumbnail %>" style="max-width: 50px;"/></td>
        <td><%= distance_of_time_in_words(from_time, album.created_at) %> ago</td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      album_path(album), :class => 'btn btn-info btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_album_path(album), :class => 'btn btn-info btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      album_path(album),
                      :method => :delete,
                      :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= paginate @albums, :theme => 'twitter-bootstrap-3' %>
</div>