config/routes.rb
Rails.application.routes.draw do
  resources :conditions
  resources :artists
  resources :albums
  resources :categories

  root to: "albums#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "VinylStars" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <a class="navbar-brand" href="<%= albums_path %>">VinylStars</a>
        <ul class="nav navbar-nav">
          <li class="nav-link"><%= link_to "Albums", albums_path  %></li>
          <li class="nav-link"><%= link_to "Artists", artists_path  %></li>
          <li class="nav-link"><%= link_to "Categories", categories_path  %></li>
          <li class="nav-link"><%= link_to "Conditions", conditions_path  %></li>
        </ul>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Vinalstar 2020</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>